name = "valid"
version = "4.1.2"

description = "A composable validation library for gleam"
licences = ["MIT"]
repository = { type = "github", user = "sporto", repo = "gleam-valid" }


[dependencies]
gleam_stdlib = "~> 0.38"
non_empty_list = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
