name = "valid"
version = "3.0.0"

description = "A validation library for gleam"
licences = ["MIT"]
repository = { type = "github", user = "sporto", repo = "gleam-validator" }


[dependencies]
gleam_stdlib = "~> 0.36"

[dev-dependencies]
gleeunit = "~> 1.0"
