name = "valid"
version = "4.1.0"

description = "A validation library for gleam"
licences = ["MIT"]
repository = { type = "github", user = "sporto", repo = "gleam-validator" }


[dependencies]
gleam_stdlib = "~> 0.36"
non_empty_list = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
