name = "valid"
version = "4.2.1"

description = "A composable validation library for gleam"
licences = ["MIT"]
repository = { type = "github", user = "sporto", repo = "gleam-valid" }


[dependencies]
gleam_stdlib = "~> 0.38"

[dev-dependencies]
gleeunit = "~> 1.0"
